# Generated by Django 5.2.8 on 2025-11-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_company_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='vacancy',
            new_name='vacancy_id',
        ),
    ]
